replicaCount: 1

image:
  repository: swirl-container-registry.palantirfoundry.com/burrito-hunter
  tag: 0.0.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
